[build]
  publish = "dist"
  command = "npm run build"

# Handle client-side routing for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects (if needed in the future)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.com/:splat"
  status = 200

[build.environment]
  REACT_APP_API_URL = "https://your-backend-url.com"
